/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Elias M. Olivares
 */
public class cartelera extends javax.swing.JFrame {

    /**
     * Creates new form cartelera
     */
    public cartelera() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        botonRapidoFurioso = new javax.swing.JButton();
        colcerCartelera = new javax.swing.JButton();
        botonAvatar = new javax.swing.JButton();
        botonChappie = new javax.swing.JButton();
        botonDemonSlayer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(239, 71, 111));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        botonRapidoFurioso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RapidoYFu.jpg"))); // NOI18N
        botonRapidoFurioso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRapidoFurioso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRapidoFuriosoActionPerformed(evt);
            }
        });
        getContentPane().add(botonRapidoFurioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 240));

        colcerCartelera.setBackground(new java.awt.Color(102, 102, 102));
        colcerCartelera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        colcerCartelera.setForeground(new java.awt.Color(255, 255, 255));
        colcerCartelera.setText("Volver");
        colcerCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colcerCarteleraActionPerformed(evt);
            }
        });
        getContentPane().add(colcerCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 390, 110, -1));

        botonAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar.jpg"))); // NOI18N
        botonAvatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAvatarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 160, 240));

        botonChappie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chapie.jpg"))); // NOI18N
        botonChappie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonChappie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonChappieActionPerformed(evt);
            }
        });
        getContentPane().add(botonChappie, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 160, 240));

        botonDemonSlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/demosSlayer.jpg"))); // NOI18N
        botonDemonSlayer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonDemonSlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDemonSlayerActionPerformed(evt);
            }
        });
        getContentPane().add(botonDemonSlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 160, 240));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cartelera");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoCartelera.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 859, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRapidoFuriosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRapidoFuriosoActionPerformed
        // TODO add your handling code here:
        questSala vantanaSala = new questSala();
        vantanaSala.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonRapidoFuriosoActionPerformed

    private void botonAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAvatarActionPerformed
        // TODO add your handling code here:
        questSala vantanaSala = new questSala();
        vantanaSala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAvatarActionPerformed

    private void botonChappieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonChappieActionPerformed
        // TODO add your handling code here:
        questSala vantanaSala = new questSala();
        vantanaSala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonChappieActionPerformed

    private void botonDemonSlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDemonSlayerActionPerformed
        // TODO add your handling code here:
        questSala vantanaSala = new questSala();
        vantanaSala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonDemonSlayerActionPerformed

    private void colcerCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colcerCarteleraActionPerformed
        // TODO add your handling code here:
        perfilPersona volverVentanaPerfil = new perfilPersona();
        volverVentanaPerfil.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_colcerCarteleraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAvatar;
    private javax.swing.JButton botonChappie;
    private javax.swing.JButton botonDemonSlayer;
    private javax.swing.JButton botonRapidoFurioso;
    private javax.swing.JButton colcerCartelera;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
