/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Elias M. Olivares
 */
public class errorDeRegistro extends javax.swing.JFrame {

    /**
     * Creates new form errorDeRegistro
     */
    public errorDeRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverVentanaError = new javax.swing.JButton();
        salirVentanaError = new javax.swing.JButton();
        registroVentanaError = new javax.swing.JButton();
        info = new javax.swing.JLabel();
        errorDeRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverVentanaError.setBackground(new java.awt.Color(6, 214, 160));
        volverVentanaError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volverVentanaError.setForeground(new java.awt.Color(255, 255, 255));
        volverVentanaError.setText("Volver");
        volverVentanaError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverVentanaErrorActionPerformed(evt);
            }
        });
        getContentPane().add(volverVentanaError, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        salirVentanaError.setBackground(new java.awt.Color(255, 51, 51));
        salirVentanaError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirVentanaError.setForeground(new java.awt.Color(255, 255, 255));
        salirVentanaError.setText("Salir");
        salirVentanaError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirVentanaErrorActionPerformed(evt);
            }
        });
        getContentPane().add(salirVentanaError, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 10, 90, 30));

        registroVentanaError.setBackground(new java.awt.Color(7, 59, 76));
        registroVentanaError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registroVentanaError.setForeground(new java.awt.Color(255, 255, 255));
        registroVentanaError.setText("Registrarse");
        registroVentanaError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroVentanaErrorActionPerformed(evt);
            }
        });
        getContentPane().add(registroVentanaError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        info.setBackground(new java.awt.Color(153, 153, 153));
        info.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setText("Usuario o contraseña no encotrado");
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 400, 30));

        errorDeRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/noSeEncuentraUsuario.jpg"))); // NOI18N
        getContentPane().add(errorDeRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroVentanaErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroVentanaErrorActionPerformed
        // TODO add your handling code here:
        registro ventanaRegistro = new registro();
        ventanaRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registroVentanaErrorActionPerformed

    private void volverVentanaErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverVentanaErrorActionPerformed
        // TODO add your handling code here:
        inicioLogo volverInicio = new inicioLogo();
        volverInicio.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_volverVentanaErrorActionPerformed

    private void salirVentanaErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirVentanaErrorActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirVentanaErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(errorDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(errorDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(errorDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(errorDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new errorDeRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorDeRegistro;
    private javax.swing.JLabel info;
    private javax.swing.JButton registroVentanaError;
    private javax.swing.JButton salirVentanaError;
    private javax.swing.JButton volverVentanaError;
    // End of variables declaration//GEN-END:variables
}
