/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Elias M. Olivares
 */
public class inicioLogo extends javax.swing.JFrame {

    /**
     * Creates new form inicioLogo
     */
    public inicioLogo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombreInicio = new javax.swing.JTextField();
        rut = new javax.swing.JLabel();
        rutInicioSesion = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        contraseñaInicio = new javax.swing.JPasswordField();
        registrar = new javax.swing.JButton();
        inicioSesionCuevana = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondoInicioSes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1632448302682.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Name :");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 60, 20));

        nombreInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreInicioActionPerformed(evt);
            }
        });
        getContentPane().add(nombreInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 200, -1));

        rut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rut.setForeground(new java.awt.Color(255, 255, 255));
        rut.setText("Rut :");
        getContentPane().add(rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 50, -1));

        rutInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutInicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(rutInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 200, -1));

        pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Pass :");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 50, -1));

        contraseñaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaInicioActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 200, -1));

        registrar.setBackground(new java.awt.Color(7, 59, 76));
        registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("Resgistrarse");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 140, -1));

        inicioSesionCuevana.setBackground(new java.awt.Color(6, 214, 160));
        inicioSesionCuevana.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inicioSesionCuevana.setForeground(new java.awt.Color(255, 255, 255));
        inicioSesionCuevana.setText("Inicio Sesion");
        inicioSesionCuevana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioSesionCuevanaActionPerformed(evt);
            }
        });
        getContentPane().add(inicioSesionCuevana, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 120, -1));

        salir.setBackground(new java.awt.Color(239, 71, 111));
        salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));

        fondoInicioSes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoInicioDeSesion.png"))); // NOI18N
        getContentPane().add(fondoInicioSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 464));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void nombreInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreInicioActionPerformed

    private void inicioSesionCuevanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioSesionCuevanaActionPerformed
        // TODO add your handling code here:
        String usuario,password,rutIni;
        usuario = nombreInicio.getText();
        rutIni = rutInicioSesion.getText();
        password = contraseñaInicio.getText();
        if (usuario.equals("Admin") && password.equals("Admin")){
            admin modoAdmin = new admin();
            modoAdmin.setVisible(true);
            this.setVisible(false);
        }else if (usuario.equals("test")&& rutIni.equals("test") && password.equals("test")){
            perfilPersona perfilUser = new perfilPersona();
            perfilUser.setVisible(true);
            this.setVisible(false);
        }else{
            errorDeRegistro ventanaError = new errorDeRegistro();
            ventanaError.setVisible(true);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_inicioSesionCuevanaActionPerformed

    private void contraseñaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaInicioActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        registro ventanaRegstrarce = new registro();
        ventanaRegstrarce.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarActionPerformed

    private void rutInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioLogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaInicio;
    private javax.swing.JLabel fondoInicioSes;
    private javax.swing.JButton inicioSesionCuevana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreInicio;
    private javax.swing.JLabel pass;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel rut;
    private javax.swing.JTextField rutInicioSesion;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
