/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Elias M. Olivares
 */
public class miniBanco extends javax.swing.JFrame {

    /**
     * Creates new form miniBanco
     */
    public miniBanco() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        okAgregarDinero = new javax.swing.JButton();
        volverBanco = new javax.swing.JButton();
        montodDinero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("$");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));

        okAgregarDinero.setBackground(new java.awt.Color(102, 102, 102));
        okAgregarDinero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        okAgregarDinero.setForeground(new java.awt.Color(255, 255, 255));
        okAgregarDinero.setText("OK");
        okAgregarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAgregarDineroActionPerformed(evt);
            }
        });
        getContentPane().add(okAgregarDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        volverBanco.setBackground(new java.awt.Color(6, 214, 160));
        volverBanco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volverBanco.setForeground(new java.awt.Color(255, 255, 255));
        volverBanco.setText("Volver");
        volverBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBancoActionPerformed(evt);
            }
        });
        getContentPane().add(volverBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        montodDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montodDineroActionPerformed(evt);
            }
        });
        getContentPane().add(montodDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agrege dinero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBancoActionPerformed
        // TODO add your handling code here:
        perfilPersona volverPersona = new perfilPersona();
        volverPersona.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverBancoActionPerformed

    private void montodDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montodDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montodDineroActionPerformed

    private void okAgregarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAgregarDineroActionPerformed
        // TODO add your handling code here:
        int agregarDinero,montoActual;
        montoActual = 0;
        agregarDinero = Integer. parseInt(montodDinero.getText());
        montoActual += agregarDinero;
        
    }//GEN-LAST:event_okAgregarDineroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miniBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miniBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miniBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miniBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miniBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField montodDinero;
    private javax.swing.JButton okAgregarDinero;
    private javax.swing.JButton volverBanco;
    // End of variables declaration//GEN-END:variables
}
