/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Elias M. Olivares
 */
public class perfilPersona extends javax.swing.JFrame {

    /**
     * Creates new form perfilPersona
     */
    public perfilPersona() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarMiniBanco = new javax.swing.JButton();
        saldoActual = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        botonVoletos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        loggoutServicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarMiniBanco.setBackground(new java.awt.Color(102, 102, 102));
        agregarMiniBanco.setForeground(new java.awt.Color(255, 255, 255));
        agregarMiniBanco.setText("Agregar Dinero");
        agregarMiniBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMiniBancoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarMiniBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        saldoActual.setEditable(false);
        saldoActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        saldoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActualActionPerformed(evt);
            }
        });
        getContentPane().add(saldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 200, -1));

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 200, -1));

        botonVoletos.setBackground(new java.awt.Color(102, 102, 102));
        botonVoletos.setForeground(new java.awt.Color(255, 255, 255));
        botonVoletos.setText("Comprar Voletos");
        botonVoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVoletosActionPerformed(evt);
            }
        });
        getContentPane().add(botonVoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        loggoutServicio.setBackground(new java.awt.Color(102, 102, 102));
        loggoutServicio.setForeground(new java.awt.Color(255, 255, 255));
        loggoutServicio.setText("Loggout");
        loggoutServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggoutServicioActionPerformed(evt);
            }
        });
        getContentPane().add(loggoutServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saldo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRegistro.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void loggoutServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggoutServicioActionPerformed
        // TODO add your handling code here:
        inicioLogo volverInicio = new inicioLogo();
        volverInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loggoutServicioActionPerformed

    private void agregarMiniBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMiniBancoActionPerformed
        // TODO add your handling code here:
        miniBanco agregarDinero = new miniBanco();
        agregarDinero.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarMiniBancoActionPerformed

    private void botonVoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVoletosActionPerformed
        // TODO add your handling code here:
        cartelera ventaPeliculas = new cartelera();
        ventaPeliculas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVoletosActionPerformed

    private void saldoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActualActionPerformed
        // TODO add your handling code here:
        int saldoDisponible =0;
        
    }//GEN-LAST:event_saldoActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarMiniBanco;
    private javax.swing.JButton botonVoletos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loggoutServicio;
    private javax.swing.JTextField saldoActual;
    // End of variables declaration//GEN-END:variables
}
