/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Elias M. Olivares
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreVentanaResistro = new javax.swing.JTextField();
        rutVentanaResistro = new javax.swing.JTextField();
        lableNombre = new javax.swing.JLabel();
        lableRut = new javax.swing.JLabel();
        lablePass = new javax.swing.JLabel();
        passwordVentanaResistro = new javax.swing.JPasswordField();
        salirVentanaRegistro = new javax.swing.JButton();
        volverVentanaRegistro = new javax.swing.JButton();
        registrarVentanaRegistro = new javax.swing.JButton();
        fondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgRegistro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 120));
        getContentPane().add(nombreVentanaResistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, -1));
        getContentPane().add(rutVentanaResistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 200, -1));

        lableNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lableNombre.setForeground(new java.awt.Color(255, 255, 255));
        lableNombre.setText("Name");
        getContentPane().add(lableNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 80, -1));

        lableRut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lableRut.setForeground(new java.awt.Color(255, 255, 255));
        lableRut.setText("Rut");
        getContentPane().add(lableRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 60, -1));

        lablePass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lablePass.setForeground(new java.awt.Color(255, 255, 255));
        lablePass.setText("Pass");
        getContentPane().add(lablePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 50, -1));
        getContentPane().add(passwordVentanaResistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 200, -1));

        salirVentanaRegistro.setBackground(new java.awt.Color(239, 71, 111));
        salirVentanaRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirVentanaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        salirVentanaRegistro.setText("Salir");
        salirVentanaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirVentanaRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(salirVentanaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 10, 90, 30));

        volverVentanaRegistro.setBackground(new java.awt.Color(239, 71, 111));
        volverVentanaRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volverVentanaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        volverVentanaRegistro.setText("Volver");
        volverVentanaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverVentanaRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(volverVentanaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 80, 30));

        registrarVentanaRegistro.setBackground(new java.awt.Color(7, 59, 76));
        registrarVentanaRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrarVentanaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        registrarVentanaRegistro.setText("Registrar");
        registrarVentanaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentanaRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(registrarVentanaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 432, 100, 30));

        fondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRegistro.jpg"))); // NOI18N
        getContentPane().add(fondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 383, 495));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarVentanaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentanaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarVentanaRegistroActionPerformed

    private void salirVentanaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirVentanaRegistroActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirVentanaRegistroActionPerformed

    private void volverVentanaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverVentanaRegistroActionPerformed
        // TODO add your handling code here:
        inicioLogo volverInicio = new inicioLogo();
        volverInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverVentanaRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lableNombre;
    private javax.swing.JLabel lablePass;
    private javax.swing.JLabel lableRut;
    private javax.swing.JTextField nombreVentanaResistro;
    private javax.swing.JPasswordField passwordVentanaResistro;
    private javax.swing.JButton registrarVentanaRegistro;
    private javax.swing.JTextField rutVentanaResistro;
    private javax.swing.JButton salirVentanaRegistro;
    private javax.swing.JButton volverVentanaRegistro;
    // End of variables declaration//GEN-END:variables
}
